### ISSUE TITLE
Update about page

### ISSUE THREAD

**Issue by Hans5958** [placeAtlas/atlas-2023#59]
### Describe the solution

I haven't touched the about page since the inception. We need updated information to it. I wonder if he still offer thos stickers...

This also includes our team members, which can be moved to the org page if it is done.

**Comment by Codixer** [comment]
<details><summary>Possible about page</summary>
<p>

Place has ended... but our project is just beginning! If you don't know us, we're the place atlas! Now, an important part for us requires the help of ***ANYONE*** who wants to help. 

For those who do not know us: 
`We're a project to document every piece on the r/place canvas. With a wiki, atlas, and following our motto "We document as it is, not how we want it to be". Our documentation efforts include policing the arguments between edits and contributions. Following the proof, facts, and widely known information about artworks.`

The most common mistake people make is not knowing we have both the wiki and atlas. So now we're making PR efforts to have the project widely known across every form of media we can find.

Now, the important part...

# What are we asking your help for?
Documenting the atlas is an enormous task that takes knowledge, we're missing most of the knowledge because we're not a part of the communities that were fighting over land in the event, we don't have the history. So we're asking you! The diplomates of your communities to provide the documentation on our atlas, our wiki and give the people the information we don't have. 

# Who can help?
Anyone! The atlas is fully open source, we allow anyone to contribute to it. You can either document it by drawing directly on the website, or by submitting a wiki article on our wiki! 

# How can you help?
Spread the atlas as far as your communities can reach, make people aware that we exist, and tell them about our documentation efforts with the entire community of r/place
Share our Reddit post ~~free karma~~. Use it to display the art that you've worked to protect!
And most of all, document the event as it happened within your community. This is what powers the atlas, it's what allowed us to serve the community with our platform and we hope to do so for many more years. 

# Links 
Discord server: https://discord.gg/r-placeatlas2-960791635342524496
Our 2023 Atlas: https://2023.place-atlas.stefanocoding.me/
Our wiki: https://place-wiki.stefanocoding.me/
Our Reddit post: https://www.reddit.com/r/place/comments/154wxvg

## Extra
Got a project you want to share? Check this post: https://www.reddit.com/r/place/comments/155lleb

</p>
</details>
